using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Unity.PlatformToolkit.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.GDK.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PlayGamesServices.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.GameKit.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PS5.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PS4.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.Steam.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.LocalSaving.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.switch.Editor")]

[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PlayGamesServices")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.GDK.Runtime")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.GameKit")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PS5.Runtime")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PS4.Runtime")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PlayMode.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.GDK.InputSystem")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.switch")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.Steam")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.LocalSaving")]

[assembly: InternalsVisibleTo("Unity.PlatformToolkit.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PlayMode.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PlayGamesServices.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.Switch.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.GameKit.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.GDK.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PS5.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PS4.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.Steam.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PlatformIndependent.Runtime.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PS4.InputSystem")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PS5.InputSystem")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.LocalSaving.Tests")]
