//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::UnityEngine.Rendering.Universal.Provider2D))]
	public class PropertyProvider_UnityEngine_Rendering_Universal_Provider2D : Unity.VisualScripting.SerializedPropertyProvider<UnityEngine.Rendering.Universal.Provider2D>
	{
	}
}
