//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Unity.Entities.Serialization.EntitySceneReference))]
	public class PropertyProvider_Unity_Entities_Serialization_EntitySceneReference : Unity.VisualScripting.SerializedPropertyProvider<Unity.Entities.Serialization.EntitySceneReference>
	{
	}
}
