//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::NPCSystem.Auth.AuthUIController.AuthStringEvent))]
	public class PropertyProvider_NPCSystem_Auth_AuthUIController_AuthStringEvent : Unity.VisualScripting.SerializedPropertyProvider<NPCSystem.Auth.AuthUIController.AuthStringEvent>
	{
	}
}
