//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::UnityEditor.Experimental.GraphView.ResizableElement.UxmlSerializedData))]
	public class PropertyProvider_UnityEditor_Experimental_GraphView_ResizableElement_UxmlSerializedData : Unity.VisualScripting.SerializedPropertyProvider<UnityEditor.Experimental.GraphView.ResizableElement.UxmlSerializedData>
	{
	}
}
