//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::UnityEngine.TextCore.Glyph))]
	public class PropertyProvider_UnityEngine_TextCore_Glyph : Unity.VisualScripting.SerializedPropertyProvider<UnityEngine.TextCore.Glyph>
	{
	}
}
