//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::UnityEngine.UIElements.Slider.UxmlSerializedData))]
	public class PropertyProvider_UnityEngine_UIElements_Slider_UxmlSerializedData : Unity.VisualScripting.SerializedPropertyProvider<UnityEngine.UIElements.Slider.UxmlSerializedData>
	{
	}
}
