//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Unity.U2D.Physics.PhysicsShape.ContactFilter))]
	public class PropertyProvider_Unity_U2D_Physics_PhysicsShape_ContactFilter : Unity.VisualScripting.SerializedPropertyProvider<Unity.U2D.Physics.PhysicsShape.ContactFilter>
	{
	}
}
