//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Unity.Mathematics.bool3x4))]
	public class PropertyProvider_Unity_Mathematics_bool3x4 : Unity.VisualScripting.SerializedPropertyProvider<Unity.Mathematics.bool3x4>
	{
	}
}
