using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PlayMode.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PlayMode.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PlayGamesServices.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PS5.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PS4.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.GameKit.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.GDK.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.GDK.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.Steam.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.Switch.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.LocalSaving.Editor")]
[assembly: InternalsVisibleTo("Unity.PlatformToolkit.PlatformIndependent.Editor.Tests")]
