// <auto-generated>Extracted from NPCDialogueNetworkBridge.cs for SRP</auto-generated>
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;

namespace NPCSystem
{
    /// <content>Dialogue request queuing, session management, and routing extracted from NPCDialogueNetworkBridge.</content>
    public partial class NPCDialogueNetworkBridge
    {
        void EnqueueDialogueRequest(ulong clientId, NPCDialogueRequestMessage request)
        {
            _pendingRequests.Enqueue(
                new PendingDialogueRequest { clientId = clientId, request = request }
            );
            LogRoutingEvent(
                clientId,
                request.requestId,
                NPCFlowStatus.Warning,
                "Dialogue request queued because another client request is in progress.",
                new Dictionary<string, object> { ["pendingRequestCount"] = _pendingRequests.Count }
            );
        }

        async Task BeginDialogueRequestAsync(ulong clientId, NPCDialogueRequestMessage request)
        {
            _activeClientId = clientId;
            _activeRequestId = request.requestId;
            await WaitForResolvedPlayerNameAsync(clientId);
            ApplySessionStateToManager(clientId);
            LogRoutingEvent(
                clientId,
                request.requestId,
                NPCFlowStatus.Start,
                $"Applying client session and switching to NPC '{request.npcSlug}' before dialogue generation."
            );
            await DialogueManager.SwitchToNPCAsync(request.npcSlug);
            DialogueManager.SendMessage(request.playerMessage);
        }

        async Task WaitForResolvedPlayerNameAsync(ulong clientId)
        {
            string initialName = ResolvePlayerDisplayName(clientId);
            if (!LooksLikeFallbackPlayerName(initialName))
            {
                return;
            }

            for (int attempt = 0; attempt < 20; attempt++)
            {
                await Task.Delay(50);
                string updatedName = ResolvePlayerDisplayName(clientId);
                if (!LooksLikeFallbackPlayerName(updatedName))
                {
                    LogClientSessionEvent(
                        clientId,
                        NPCFlowStatus.Success,
                        $"Resolved player display name to '{updatedName}' before dialogue generation."
                    );
                    return;
                }
            }

            LogClientSessionEvent(
                clientId,
                NPCFlowStatus.Warning,
                $"Player display name still unresolved before dialogue generation. Using fallback '{ResolvePlayerDisplayName(clientId)}'."
            );
        }

        void TryProcessNextQueuedRequest()
        {
            if (
                _activeClientId.HasValue
                || DialogueManager == null
                || SessionManager == null
                || !Application.isPlaying
            )
                return;

            while (_pendingRequests.Count > 0)
            {
                PendingDialogueRequest pending = _pendingRequests.Dequeue();
                if (
                    !SessionManager.TryGetSelectedNpcSlug(
                        pending.clientId,
                        out string selectedNpcSlug
                    ) || string.IsNullOrWhiteSpace(selectedNpcSlug)
                )
                {
                    continue;
                }

                pending.request.npcSlug = selectedNpcSlug;
                _ = BeginDialogueRequestAsync(pending.clientId, pending.request);
                break;
            }
        }

        void RemoveQueuedRequestsForClient(ulong clientId)
        {
            if (_pendingRequests.Count == 0)
                return;

            var preservedRequests = new Queue<PendingDialogueRequest>();
            while (_pendingRequests.Count > 0)
            {
                PendingDialogueRequest pending = _pendingRequests.Dequeue();
                if (pending.clientId != clientId)
                {
                    preservedRequests.Enqueue(pending);
                }
            }

            while (preservedRequests.Count > 0)
            {
                _pendingRequests.Enqueue(preservedRequests.Dequeue());
            }
        }

        void EnsureClientSessionSeeded(ulong clientId)
        {
            if (SessionManager == null)
                return;
            if (DialogueManager != null && _baselineHistorySnapshot.Count == 0)
            {
                CaptureBaselineState();
            }

            string playerDisplayName = ResolvePlayerDisplayName(clientId);
            if (SessionManager.HasSession(clientId))
                return;

            SessionManager.SetAllHistorySnapshots(
                clientId,
                CloneHistorySnapshot(_baselineHistorySnapshot)
            );
            SessionManager.SetEvidenceSnapshot(
                clientId,
                _baselineEvidenceSnapshot?.Clone() ?? new NPCEvidenceStateSnapshot()
            );
            SessionManager.SetPlayerDisplayName(clientId, playerDisplayName);
            LogClientSessionEvent(
                clientId,
                NPCFlowStatus.Success,
                $"Seeded new client session for '{playerDisplayName}'."
            );
        }

        void ApplySessionStateToManager(ulong clientId)
        {
            if (DialogueManager == null || SessionManager == null)
                return;
            SessionManager.SetPlayerDisplayName(clientId, ResolvePlayerDisplayName(clientId));
            DialogueManager.ApplyHistorySnapshot(SessionManager.GetAllHistorySnapshots(clientId));
            DialogueManager.ApplyEvidenceSnapshot(SessionManager.GetEvidenceSnapshot(clientId));
            DialogueManager.SetRuntimePlayerContext(
                SessionManager.GetPlayerDisplayName(clientId),
                clientId
            );
            LogClientSessionEvent(
                clientId,
                NPCFlowStatus.Success,
                $"Applied session to dialogue manager for '{SessionManager.GetPlayerDisplayName(clientId)}'."
            );
        }

        void SyncSessionFromManagerState(ulong clientId)
        {
            if (DialogueManager == null || SessionManager == null)
                return;
            SessionManager.SetAllHistorySnapshots(
                clientId,
                DialogueManager.CaptureHistorySnapshot()
            );
            SessionManager.SetEvidenceSnapshot(clientId, DialogueManager.CaptureEvidenceSnapshot());
            LogClientSessionEvent(
                clientId,
                NPCFlowStatus.Success,
                $"Synchronized dialogue manager state back into session cache for '{SessionManager.GetPlayerDisplayName(clientId)}'."
            );
        }
    }
}
