// <auto-generated>Extracted from NPCDialogueNetworkBridge.cs for SRP</auto-generated>
using System;
using System.Collections.Generic;

namespace NPCSystem
{
    /// <content>Notebook state tracking and synchronization extracted from NPCDialogueNetworkBridge.</content>
    public partial class NPCDialogueNetworkBridge
    {
        NPCNotebookStateMessage _currentNotebookState;
        readonly Dictionary<string, List<DialogueEntry>> _baselineHistorySnapshot =
            new Dictionary<string, List<DialogueEntry>>(StringComparer.OrdinalIgnoreCase);
        NPCEvidenceStateSnapshot _baselineEvidenceSnapshot = new NPCEvidenceStateSnapshot();

        public NPCNotebookStateMessage CurrentNotebookState => _currentNotebookState;

        NPCNotebookStateMessage BuildNotebookStateMessage()
        {
            return NPCNotebookStateFormatter.Build(
                dialogueManager != null
                    ? dialogueManager.CaptureEvidenceSnapshot()
                    : new NPCEvidenceStateSnapshot(),
                dialogueManager != null && dialogueManager.currentProfile != null
                    ? dialogueManager.currentProfile.GetNpcSlug()
                    : _localSelectedNpcSlug
            );
        }

        void UpdateNotebookStateLocal()
        {
            if (!ShouldRelayLocally())
                return;
            _currentNotebookState = BuildNotebookStateMessage();
            OnNotebookStateChanged?.Invoke(_currentNotebookState);
        }

        NPCNotebookStateMessage BuildNotebookStateMessageForClient(ulong clientId)
        {
            string selectedNpcSlug = string.Empty;
            if (sessionManager != null)
            {
                sessionManager.TryGetSelectedNpcSlug(clientId, out selectedNpcSlug);
            }

            return NPCNotebookStateFormatter.Build(
                sessionManager != null
                    ? sessionManager.GetEvidenceSnapshot(clientId)
                    : new NPCEvidenceStateSnapshot(),
                selectedNpcSlug
            );
        }

        public void RefreshNotebookStateForClient(ulong clientId)
        {
            if (!IsServer || NetworkManager == null || !NetworkManager.IsListening)
            {
                return;
            }

            SendNotebookStateToClient(clientId, BuildNotebookStateMessageForClient(clientId));
        }

        void CaptureBaselineState()
        {
            if (dialogueManager == null)
                return;
            _baselineHistorySnapshot = CloneHistorySnapshot(
                dialogueManager.CaptureHistorySnapshot()
            );
            _baselineEvidenceSnapshot =
                dialogueManager.CaptureEvidenceSnapshot()?.Clone()
                ?? new NPCEvidenceStateSnapshot();
        }
    }
}
