// <auto-generated>Extracted from NPCDialogueNetworkBridge.cs for SRP</auto-generated>
using System;
using System.Collections.Generic;

namespace NPCSystem
{
    /// <content>Notebook state tracking and synchronization extracted from NPCDialogueNetworkBridge.</content>
    public partial class NPCDialogueNetworkBridge
    {
        NPCNotebookStateMessage _currentNotebookState;
        Dictionary<string, List<DialogueEntry>> _baselineHistorySnapshot =
            new Dictionary<string, List<DialogueEntry>>(StringComparer.OrdinalIgnoreCase);
        NPCEvidenceStateSnapshot _baselineEvidenceSnapshot = new NPCEvidenceStateSnapshot();

        public NPCNotebookStateMessage CurrentNotebookState => _currentNotebookState;

        NPCNotebookStateMessage BuildNotebookStateMessage()
        {
            return NPCNotebookStateFormatter.Build(
                DialogueManager != null
                    ? DialogueManager.CaptureEvidenceSnapshot()
                    : new NPCEvidenceStateSnapshot(),
                DialogueManager != null && DialogueManager.currentProfile != null
                    ? DialogueManager.currentProfile.GetNpcSlug()
                    : _localSelectedNpcSlug
            );
        }

        void UpdateNotebookStateLocal()
        {
            if (!ShouldRelayLocally())
                return;
            _currentNotebookState = BuildNotebookStateMessage();
            OnNotebookStateChanged?.Invoke(_currentNotebookState);
        }

        NPCNotebookStateMessage BuildNotebookStateMessageForClient(ulong clientId)
        {
            string selectedNpcSlug = string.Empty;
            if (SessionManager != null)
            {
                SessionManager.TryGetSelectedNpcSlug(clientId, out selectedNpcSlug);
            }

            return NPCNotebookStateFormatter.Build(
                SessionManager != null
                    ? SessionManager.GetEvidenceSnapshot(clientId)
                    : new NPCEvidenceStateSnapshot(),
                selectedNpcSlug
            );
        }

        public void RefreshNotebookStateForClient(ulong clientId)
        {
            if (!IsServer || NetworkManager == null || !NetworkManager.IsListening)
            {
                return;
            }

            SendNotebookStateToClient(clientId, BuildNotebookStateMessageForClient(clientId));
        }

        void CaptureBaselineState()
        {
            if (DialogueManager == null)
                return;
            _baselineHistorySnapshot = CloneHistorySnapshot(
                DialogueManager.CaptureHistorySnapshot()
            );
            _baselineEvidenceSnapshot =
                DialogueManager.CaptureEvidenceSnapshot()?.Clone()
                ?? new NPCEvidenceStateSnapshot();
        }
    }
}
