// <auto-generated>Extracted from NPCDialogueNetworkBridge.cs for SRP</auto-generated>
using System;
using System.Collections.Generic;
using Unity.Netcode;
using UnityEngine;

namespace NPCSystem
{
    /// <content>NPC profile lookup, display name resolution, and snapshot cloning extracted from NPCDialogueNetworkBridge.</content>
    public partial class NPCDialogueNetworkBridge
    {
        public NPCProfile[] Profiles =>
            _dialogueManager == null ? Array.Empty<NPCProfile>() : _dialogueManager.Profiles;
        public NPCProfile CurrentProfile
        {
            get
            {
                if (
                    _dialogueManager != null
                    && (
                        !Application.isPlaying
                        || NetworkManager == null
                        || !NetworkManager.IsListening
                        || IsServer
                    )
                )
                {
                    return _dialogueManager.CurrentProfile;
                }

                return FindProfileBySlug(_localSelectedNpcSlug);
            }
        }

        public NPCProfile FindProfileBySlug(string npcSlug)
        {
            if (_dialogueManager == null || string.IsNullOrWhiteSpace(npcSlug))
                return null;

            foreach (NPCProfile profile in _dialogueManager.Profiles)
            {
                if (
                    profile != null
                    && string.Equals(
                        profile.GetNpcSlug(),
                        npcSlug.Trim(),
                        StringComparison.OrdinalIgnoreCase
                    )
                )
                {
                    return profile;
                }
            }

            return null;
        }

        public static Dictionary<string, List<DialogueEntry>> CloneHistorySnapshot(
            Dictionary<string, List<DialogueEntry>> historyByNpc
        )
        {
            var clone = new Dictionary<string, List<DialogueEntry>>(
                StringComparer.OrdinalIgnoreCase
            );
            foreach (
                var pair in historyByNpc
                    ?? new Dictionary<string, List<DialogueEntry>>(StringComparer.OrdinalIgnoreCase)
            )
            {
                List<DialogueEntry> entries = new List<DialogueEntry>();
                foreach (DialogueEntry entry in pair.Value ?? new List<DialogueEntry>())
                {
                    if (entry == null)
                        continue;
                    entries.Add(
                        new DialogueEntry
                        {
                            role = entry.role,
                            content = entry.content,
                            timestampUtc = entry.timestampUtc,
                        }
                    );
                }
                clone[pair.Key] = entries;
            }

            return clone;
        }

        string ResolvePlayerDisplayName(ulong clientId)
        {
            if (
                NetworkManager == null
                || !NetworkManager.ConnectedClients.TryGetValue(clientId, out NetworkClient client)
            )
            {
                return $"Player {clientId}";
            }

            NetworkObject playerObject = client.PlayerObject;
            if (playerObject == null)
            {
                return $"Player {clientId}";
            }

            NPCPlayerNetworkAvatar avatar = playerObject.GetComponent<NPCPlayerNetworkAvatar>();
            return avatar != null ? avatar.DisplayName : $"Player {clientId}";
        }

        public static bool LooksLikeFallbackPlayerName(string playerName)
        {
            if (string.IsNullOrWhiteSpace(playerName))
                return true;

            string normalized = playerName.Trim();
            if (!normalized.StartsWith("Player ", StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            return ulong.TryParse(normalized.Substring("Player ".Length), out _);
        }
    }
}
