// <auto-generated>Extracted from NPCDialogueNetworkBridge.cs for SRP</auto-generated>
using System.Collections.Generic;
using Unity.Netcode;
using UnityEngine;

namespace NPCSystem
{
    /// <content>Response relay and routing logic extracted from NPCDialogueNetworkBridge.</content>
    public partial class NPCDialogueNetworkBridge
    {
        string ActiveClientPreview =>
            _activeClientId.HasValue ? _activeClientId.Value.ToString() : "<none>";

        int PendingRequestCount => _pendingRequests.Count;

        void HandleManagerNpcChanged(string displayName)
        {
            if (ShouldRelayLocally())
            {
                OnNpcChanged?.Invoke(displayName);
                UpdateNotebookStateLocal();
            }
        }

        void HandleManagerResponseStart(string playerMessage)
        {
            if (
                _activeClientId.HasValue
                && IsServer
                && NetworkManager != null
                && NetworkManager.IsListening
            )
            {
                var payload = BuildResponsePayload(playerMessage);
                LogRoutingEvent(
                    _activeClientId.Value,
                    _activeRequestId,
                    NPCFlowStatus.Start,
                    "Relaying response-start event to requesting client."
                );
                SendResponseStartToClient(_activeClientId.Value, payload);
                return;
            }

            if (ShouldRelayLocally())
            {
                OnResponseStart?.Invoke(playerMessage);
            }
        }

        void HandleManagerResponseUpdated(string partialResponse)
        {
            if (
                _activeClientId.HasValue
                && IsServer
                && NetworkManager != null
                && NetworkManager.IsListening
            )
            {
                var payload = BuildResponsePayload(partialResponse);
                LogRoutingEvent(
                    _activeClientId.Value,
                    _activeRequestId,
                    NPCFlowStatus.Start,
                    "Relaying response-update event to requesting client."
                );
                SendResponseUpdatedToClient(_activeClientId.Value, payload);
                return;
            }

            if (ShouldRelayLocally())
            {
                OnResponseUpdated?.Invoke(partialResponse);
            }
        }

        void HandleManagerResponseComplete(string npcDisplayName, string response)
        {
            if (
                _activeClientId.HasValue
                && IsServer
                && NetworkManager != null
                && NetworkManager.IsListening
            )
            {
                ulong clientId = _activeClientId.Value;
                SyncSessionFromManagerState(clientId);

                // Try to detect and perform verbal item transfer
                TryVerbalItemTransfer(clientId, response);

                var payload = BuildResponsePayload(response);
                payload.displayName = npcDisplayName;
                LogRoutingEvent(
                    clientId,
                    _activeRequestId,
                    NPCFlowStatus.Success,
                    "Relaying completed NPC response to requesting client."
                );
                SendResponseCompleteToClient(clientId, payload);
                SendNotebookStateToClient(clientId, BuildNotebookStateMessage());
                _activeClientId = null;
                _activeRequestId = string.Empty;
                TryProcessNextQueuedRequest();
                return;
            }

            if (ShouldRelayLocally())
            {
                OnResponseComplete?.Invoke(npcDisplayName, response);
                UpdateNotebookStateLocal();
            }
        }

        void HandleManagerError(string error)
        {
            if (
                _activeClientId.HasValue
                && IsServer
                && NetworkManager != null
                && NetworkManager.IsListening
            )
            {
                ulong clientId = _activeClientId.Value;
                SyncSessionFromManagerState(clientId);
                LogRoutingEvent(
                    clientId,
                    _activeRequestId,
                    NPCFlowStatus.Error,
                    $"Relaying dialogue error to requesting client: {error}"
                );
                SendErrorToClient(clientId, error);
                _activeClientId = null;
                _activeRequestId = string.Empty;
                TryProcessNextQueuedRequest();
                return;
            }

            if (ShouldRelayLocally())
            {
                OnError?.Invoke(error);
            }
        }

        public bool ShouldRelayLocally()
        {
            return !Application.isPlaying
                || NetworkManager == null
                || !NetworkManager.IsListening
                || IsServer;
        }

        void RaiseErrorLocal(string error)
        {
            if (!string.IsNullOrWhiteSpace(error))
            {
                OnError?.Invoke(error);
            }
        }

        NPCDialogueResponseMessage BuildResponsePayload(string content)
        {
            return new NPCDialogueResponseMessage
            {
                requestId = _activeRequestId,
                npcSlug =
                    dialogueManager != null && dialogueManager.currentProfile != null
                        ? dialogueManager.currentProfile.GetNpcSlug()
                        : _localSelectedNpcSlug,
                displayName =
                    dialogueManager != null && dialogueManager.currentProfile != null
                        ? dialogueManager.currentProfile.GetDisplayName()
                    : currentProfile != null ? currentProfile.GetDisplayName()
                    : string.Empty,
                content = NPCFlowTextSanitizer.CleanDialogueText(content),
            };
        }
    }
}
