// <auto-generated>Extracted from NPCDialogueUIController.cs for SRP</auto-generated>
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace NPCSystem
{
    /// <content>Runtime event handlers, profile selection, and portrait updates extracted from NPCDialogueUIController.</content>
    public partial class NPCDialogueUIController
    {
        void HandleNpcChanged(string displayName)
        {
            UpdatePortrait(GetActiveProfile());
            _readyForInput = true;
            SetInputEnabled(true);
        }

        void HandleResponseStart(string playerMessage)
        {
            NPCFlowLogger
                .FindOrCreate()
                .Log(
                    NPCFlowStage.UIInput,
                    NPCFlowStatus.Success,
                    NPCFlowLogLevel.Info,
                    "UI received response-start event.",
                    source: nameof(NPCDialogueUIController),
                    npcSlug: GetActiveProfile() != null ? GetActiveProfile().GetNpcSlug() : null,
                    data: NPCFlowTextSanitizer.MergeSummary(
                        new Dictionary<string, object>(),
                        "player",
                        playerMessage,
                        false,
                        0
                    )
                );
            if (PlayerInput != null)
                PlayerInput.interactable = false;
            SetAIText("...");
        }

        void HandleResponseComplete(string npcName, string response)
        {
            NPCFlowLogger
                .FindOrCreate()
                .Log(
                    NPCFlowStage.ResponseComplete,
                    NPCFlowStatus.Success,
                    NPCFlowLogLevel.Info,
                    "UI received response-complete event.",
                    source: nameof(NPCDialogueUIController),
                    npcSlug: npcName,
                    data: NPCFlowTextSanitizer.MergeSummary(
                        new Dictionary<string, object>(),
                        "response",
                        response,
                        false,
                        0
                    )
                );
            SetAIText(response);
            SetInputEnabled(true);
            if (PlayerInput != null)
                PlayerInput.text = "";
        }

        void HandleError(string error)
        {
            string normalizedError = string.IsNullOrWhiteSpace(error)
                ? "Unknown dialogue error."
                : error.Trim();
            NPCFlowLogger
                .FindOrCreate()
                .Log(
                    NPCFlowStage.UIInput,
                    NPCFlowStatus.Error,
                    NPCFlowLogLevel.Error,
                    $"UI received dialogue error: {normalizedError}",
                    source: nameof(NPCDialogueUIController),
                    data: new Dictionary<string, object> { ["error"] = normalizedError }
                );
            SetAIText($"Error: {normalizedError}");
            if (GetActiveProfile() != null)
            {
                _readyForInput = true;
                SetInputEnabled(true);
            }
        }

        void OnCharacterSelectionChanged(int selection)
        {
            _ = SelectProfileAsync(selection);
        }

        async System.Threading.Tasks.Task SelectProfileAsync(int selection)
        {
            if (selection < 0 || selection >= _profiles.Count)
            {
                NPCFlowLogger
                    .FindOrCreate()
                    .Log(
                        NPCFlowStage.NPCSwitch,
                        NPCFlowStatus.Skipped,
                        NPCFlowLogLevel.Warning,
                        "UI profile selection index out of range.",
                        source: nameof(NPCDialogueUIController),
                        data: new Dictionary<string, object>
                        {
                            ["selection"] = selection,
                            ["profileCount"] = _profiles.Count,
                        }
                    );
                return;
            }

            string npcSlug = _profiles[selection].GetNpcSlug();
            if (NetworkBridge != null)
                await NetworkBridge.RequestNpcSelectionAsync(npcSlug);
            else
                await DialogueManager.SwitchToNPCAsync(npcSlug);
        }

        void UpdatePortrait(NPCProfile profile)
        {
            RawImage[] portraits = new[] { ButlerImage, MaidImage, ChefImage };
            if (profile == null)
            {
                foreach (RawImage img in portraits)
                {
                    if (img != null)
                        img.CrossFadeAlpha(0f, 0.15f, true);
                }
                return;
            }

            string slug = profile.GetNpcSlug();
            for (int i = 0; i < portraits.Length; i++)
            {
                if (portraits[i] == null)
                    continue;

                if (
                    (slug == "butler" && i == 0)
                    || (slug == "maid" && i == 1)
                    || (slug == "chef" && i == 2)
                )
                {
                    if (profile.PortraitTexture != null)
                        portraits[i].texture = profile.PortraitTexture;
                    portraits[i].CrossFadeAlpha(1f, 0.15f, true);
                }
                else
                {
                    portraits[i].CrossFadeAlpha(0f, 0.15f, true);
                }
            }
        }

        void OnInputFieldSubmit(string text)
        {
            if (!_readyForInput)
                return;

            string message = (text ?? string.Empty).Trim();
            if (message.Length == 0)
                return;

            if (PlayerInput != null)
                PlayerInput.interactable = false;

            if (NetworkBridge != null)
                NetworkBridge.SubmitPlayerMessage(message);
            else
                DialogueManager.SendMessage(message);
        }

        void OnStopPressed()
        {
            if (NetworkBridge != null)
                NetworkBridge.CancelActiveRequest();
            else
                DialogueManager.CancelRequests();
            SetAIText(string.Empty);
            SetInputEnabled(true);
        }
    }
}
