// <auto-generated>Extracted from NPCDialogueUIController.cs for SRP</auto-generated>
using System.Linq;
using EditorAttributes;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace NPCSystem
{
    /// <content>Auto-find component references extracted from NPCDialogueUIController.</content>
    public partial class NPCDialogueUIController
    {
        [Button("Auto-Assign References")]
        void AutoAssignReferences()
        {
            ResolveReferences();
        }

        [Button("Validate UI References")]
        void ValidateUiReferences()
        {
            NPCFlowLogger
                .FindOrCreate()
                .Log(
                    NPCFlowStage.ConfigurationValidation,
                    DialogueManager != null ? NPCFlowStatus.Success : NPCFlowStatus.Warning,
                    DialogueManager != null ? NPCFlowLogLevel.Info : NPCFlowLogLevel.Warning,
                    DialogueManager != null
                        ? "NPCDialogueManager is assigned."
                        : "NPCDialogueManager is NOT assigned — runtime will not function.",
                    source: nameof(NPCDialogueUIController)
                );
        }

        void ResolveReferences()
        {
            if (DialogueManager == null)
            {
                DialogueManager = GetComponent<NPCDialogueManager>();
                if (DialogueManager == null)
                {
                    DialogueManager = FindAnyObjectByType<NPCDialogueManager>(
                        FindObjectsInactive.Include
                    );
                }
            }

            if (NetworkBridge == null)
            {
                NetworkBridge = GetComponent<NPCDialogueNetworkBridge>();
                if (NetworkBridge == null)
                {
                    NetworkBridge = FindAnyObjectByType<NPCDialogueNetworkBridge>(
                        FindObjectsInactive.Include
                    );
                }
            }

            if (LegacyKnowledgeBaseController == null)
            {
                LegacyKnowledgeBaseController = FindObjectsByType<Behaviour>(
                        FindObjectsInactive.Include
                    )
                    .FirstOrDefault(behaviour =>
                        behaviour != null
                        && behaviour.GetType().FullName == "LLMUnitySamples.KnowledgeBaseGame"
                    );
            }

            CharacterSelect =
                CharacterSelect != null
                    ? CharacterSelect
                    : FindComponent<TMP_Dropdown>(this, "Canvas/Dropdown");
            PlayerInput =
                PlayerInput != null
                    ? PlayerInput
                    : FindComponent<TMP_InputField>(this, "Canvas/PlayerInput");
            AiText = AiText != null ? AiText : FindComponent<TMP_Text>(this, "Canvas/AIImage/AIText");
            StopButton =
                StopButton != null ? StopButton : FindComponent<Button>(this, "Canvas/StopButton");

            ButlerImage =
                ButlerImage != null ? ButlerImage : FindComponent<RawImage>(this, "Canvas/ButlerImage");
            MaidImage = MaidImage != null ? MaidImage : FindComponent<RawImage>(this, "Canvas/MaidImage");
            ChefImage = ChefImage != null ? ChefImage : FindComponent<RawImage>(this, "Canvas/ChefImage");

            NotebookController =
                NotebookController != null
                    ? NotebookController
                    : FindAnyObjectByType<NotebookUIController>(FindObjectsInactive.Include);
            ExitButton =
                ExitButton != null ? ExitButton : FindComponent<Button>(this, "Canvas/ExitButton");
        }
    }
}
