// <auto-generated>Extracted from NPCDialogueUIController.cs for SRP</auto-generated>
using System.Linq;
using UnityEngine;

namespace NPCSystem
{
    /// <content>Async initialization orchestration extracted from NPCDialogueUIController.</content>
    public partial class NPCDialogueUIController
    {
        async System.Threading.Tasks.Task InitializeOnDemandInternalAsync()
        {
            NPCFlowLogger
                .FindOrCreate()
                .Log(
                    NPCFlowStage.SceneBootstrap,
                    NPCFlowStatus.Start,
                    NPCFlowLogLevel.Debug,
                    "NPCDialogueUIController starting on demand.",
                    source: nameof(NPCDialogueUIController)
                );

            ResolveReferences();
            DisableLegacyController();
            SetInputEnabled(false);
            BindUiListeners();

            try
            {
                var bootstrapper = FindAnyObjectByType<NPCDialogueBootstrapper>(
                    FindObjectsInactive.Include
                );
                if (bootstrapper != null)
                {
                    await bootstrapper.InitializeOnDemandAsync();
                }
                else
                {
                    if (NetworkBridge == null && DialogueManager == null)
                    {
                        NPCFlowLogger
                            .FindOrCreate()
                            .Log(
                                NPCFlowStage.SceneBootstrap,
                                NPCFlowStatus.Error,
                                NPCFlowLogLevel.Error,
                                "Neither NPCDialogueManager nor NPCDialogueNetworkBridge is available.",
                                source: nameof(NPCDialogueUIController)
                            );
                        return;
                    }

                    if (NetworkBridge != null)
                        await NetworkBridge.InitializeAsync();
                    else
                        await DialogueManager.InitializeAsync();
                }

                BindRuntimeEvents();
                PopulateDropdown();
                await SyncDropdownToCurrentProfileAsync();
            }
            catch (System.Exception ex)
            {
                NPCFlowLogger
                    .FindOrCreate()
                    .Log(
                        NPCFlowStage.SceneBootstrap,
                        NPCFlowStatus.Fallback,
                        NPCFlowLogLevel.Warning,
                        $"Dialogue bootstrap init failed: {ex.Message}. Input still enabled.",
                        source: nameof(NPCDialogueUIController)
                    );
            }
            finally
            {
                _readyForInput = true;
                SetInputEnabled(true);
                if (PlayerInput != null)
                {
                    PlayerInput.Select();
                    PlayerInput.ActivateInputField();
                }
            }

            NPCFlowLogger
                .FindOrCreate()
                .Log(
                    NPCFlowStage.SceneBootstrap,
                    NPCFlowStatus.Success,
                    NPCFlowLogLevel.Debug,
                    "NPCDialogueUIController ready and initialized.",
                    source: nameof(NPCDialogueUIController)
                );
        }

        void PopulateDropdown()
        {
            NPCProfile[] availableProfiles =
                NetworkBridge != null ? NetworkBridge.Profiles : DialogueManager.Profiles;
            _profiles = availableProfiles.Where(profile => profile != null).ToList();
            if (CharacterSelect == null)
                return;

            CharacterSelect.ClearOptions();
            CharacterSelect.AddOptions(
                _profiles.Select(profile => profile.GetDisplayName()).ToList()
            );
        }

        async System.Threading.Tasks.Task SyncDropdownToCurrentProfileAsync()
        {
            if (
                (DialogueManager == null && NetworkBridge == null)
                || CharacterSelect == null
                || _profiles.Count == 0
            )
                return;

            NPCProfile activeProfile = GetActiveProfile();
            if (activeProfile == null)
            {
                CharacterSelect.SetValueWithoutNotify(0);
                await SelectProfileAsync(0);
                return;
            }

            int index = _profiles.FindIndex(profile => profile == activeProfile);
            if (index < 0)
                index = 0;
            CharacterSelect.SetValueWithoutNotify(index);
            UpdatePortrait(activeProfile);
            SetInputEnabled(true);
            _readyForInput = true;
        }

        void DisableLegacyController()
        {
            if (LegacyKnowledgeBaseController != null)
            {
                LegacyKnowledgeBaseController.enabled = false;
            }
        }
    }
}
